RemoteCourses/Controllers/ContentsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using RemoteCourses.Models;
using RemoteCourses.Repositories.EntityFramework;

namespace RemoteCourses.Controllers
{
    public class ContentsController : Controller
    {
        private CourseContext db = new CourseContext();
        private Content _content;

        // GET: Contents
        public ActionResult Index(string sectionId)
        {
            if (sectionId != null)
            {
                var id = int.Parse(sectionId);
                var content = db.Contents.FirstOrDefault(c => c.Sections.Id == id);
                _content = content;
            }

            return View(_content);
        }

        // GET: Contents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // GET: Contents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,ContentText")] Content content)
        {
            if (ModelState.IsValid)
            {
                db.Contents.Add(content);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(content);
        }

        // GET: Contents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: Contents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,ContentText")] Content content)
        {
            if (ModelState.IsValid)
            {
                db.Entry(content).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(content);
        }

        // GET: Contents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: Contents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Content content = db.Contents.Find(id);
            db.Contents.Remove(content);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RemoteCourses/Controllers/CoursesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;
using RemoteCourses.Repositories.EntityFramework;
using RemoteCourses.Utils;

namespace RemoteCourses.Controllers
{
    public class CoursesController : Controller
    {
        private CourseContext db = new CourseContext();

        // GET: Courses
        public ActionResult Index(string courseId)
        {
            var name = GetAuthStudent();

            if (courseId != null && courseId != "")
            {
                var id = int.Parse(courseId);
                var course = db.Courses.FirstOrDefault(c => c.Id == id);
                var student = db.Students.FirstOrDefault(s => s.Name == name);

                student.Courses.Add(course);
                db.SaveChanges();
            }

            var courses = db.Courses.Where(c => c.Students.Any(s => s.Name == name)).Include(c => c.Section);

            return View(courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var course = db.Courses.Include(c => c.Section).FirstOrDefault(x => x.Id == id);

            if (course == null)
            {
                return HttpNotFound();
            }

            return View(course);
        }

        //// GET: Courses/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Courses/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Title,Description")] Course course)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Courses.Add(course);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(course);
        //}

        //// GET: Courses/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Course course = db.Courses.Find(id);
        //    if (course == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(course);
        //}

        //// POST: Courses/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Title,Description")] Course course)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(course).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(course);
        //}

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var name = GetAuthStudent();

            var course = db.Courses.FirstOrDefault(c => c.Id == id);
            var student = db.Students.FirstOrDefault(s => s.Name == name);

            student.Courses.Remove(course);
            db.SaveChanges();

            var courses = db.Courses.Where(c => c.Students.Any(s => s.Name == name)).Include(c => c.Section);

            return RedirectToAction("Index");
        }

        //// POST: Courses/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Course course = db.Courses.Find(id);
        //    db.Courses.Remove(course);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        

        // USUNAC DELETE W KURSACH


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string GetAuthStudent()
        {
            var cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            var studnet = AccountUtils.AuthenticatedUser(cookie);

            return studnet != null ? studnet.Name : null;
        }
    }
}

RemoteCourses/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;
using RemoteCourses.Models;
using RemoteCourses.Repositories.EntityFramework;
using RemoteCourses.Utils;

namespace RemoteCourses.Controllers
{
    public class QuestionsController : Controller
    {
        private CourseContext db = new CourseContext();
        private IEnumerable<Question> _questions;
        private Section _section;

        // GET: Questions
        public ActionResult Index(string sectionId)
        {
            if (sectionId != null)
            {
                var id = int.Parse(sectionId);
                var questions = db.Questions.Where(q => q.Sections.Id == id);
                _questions = questions;
            }

            return View(_questions.ToList());
        }

        public ActionResult QuizForm(string question1, string question2, string question3)
        {
            var studentName = GetAuthStudent();
            var student = db.Students.FirstOrDefault(s => s.Name == studentName);
            //var sections = db.Sections;

            string[] outputQuestion1 = question1.Split(';');
            string[] outputQuestion2 = question2.Split(';');
            string[] outputQuestion3 = question3.Split(';');

            Dictionary<int, string> questiondict = new Dictionary<int, string>() 
            { 
                { int.Parse(outputQuestion1[0]), outputQuestion1[1] },
                { int.Parse(outputQuestion2[0]), outputQuestion2[1] },
                { int.Parse(outputQuestion3[0]), outputQuestion3[1] }
            };

            int correctAnswerCounter = 0;
            int allAnswers = 0;
            int sectionId = 0;

            foreach (var compare in questiondict)
            {
                var question = db.Questions.FirstOrDefault(q => q.Id == compare.Key);

                if (question.CorrectAnswer == compare.Value)
                {
                    correctAnswerCounter++;
                    allAnswers++;
                }
                else
                {
                    allAnswers++;
                }

                sectionId = db.Sections.FirstOrDefault(s => s.Questions.FirstOrDefault(q => q.Id == question.Id).Sections.Id == s.Id).Id;
                _section = db.Sections.FirstOrDefault(s => s.Questions.FirstOrDefault(q => q.Id == question.Id).Sections.Id == s.Id);
            }

            var result = new Result() { Score = correctAnswerCounter, TotalQuestions = allAnswers, DateTaken = DateTime.Now, Student_Id = student.Id, Sections = _section };
            db.Results.Add(result);
            db.SaveChanges();

            return RedirectToAction("Index", "Results");
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Text,CorrectAnswer")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Text,CorrectAnswer")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string GetAuthStudent()
        {
            var cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            var student = AccountUtils.AuthenticatedUser(cookie);

            return student != null ? student.Name : null;
        }
    }
}

RemoteCourses/Views/Courses/Create.cshtml
@model RemoteCourses.Models.Course

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RemoteCourses/Views/Courses/Delete.cshtml
@model RemoteCourses.Models.Course

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RemoteCourses/Views/Courses/Details.cshtml
@model RemoteCourses.Models.Course

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

    List<SelectListItem> itemList = new List<SelectListItem>();

    foreach (var section in Model.Section)
    {
        itemList.Add(new SelectListItem() { Text = section.SectionName, Value = section.Id.ToString() });
    }

}

<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="../../img/bg.jpg">
    <div class="container hero-text text-white">

        <h2>Kurs</h2>

        <div>
            <dl class="dl-horizontal">
                <dt>
                    Kategoria
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    Opis
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>

        <hr />
        <h3>Rozdziały</h3>

        @using (Html.BeginForm("Index", "Contents", FormMethod.Post))
        {
            <div class="form-actions no-color">
                <div class="form-inline">
                    @Html.DropDownList("sectionId", new SelectList(itemList, "Value", "Text"), "Wybierz rozdział", new { @class = "form-control" })
                    <input type="submit" value="Wybierz" class="btn btn-info" />
                </div>
            </div>
        }

        <hr />
        <h3>Quizy</h3>
        @using (Html.BeginForm("Index", "Questions", FormMethod.Post))
        {
            <div class="form-actions no-color">
                <div class="form-inline">
                    @Html.DropDownList("sectionId", new SelectList(itemList, "Value", "Text"), "Wybierz quiz", new { @class = "form-control" })
                    <input type="submit" value="Wybierz" class="btn btn-info" />
                </div>
            </div>
        }

        <hr />
        <p>
            @Html.ActionLink("Powrót", "Index")
        </p>

    </div>
</section>
<!-- Hero section end -->

RemoteCourses/Views/Courses/Edit.cshtml
@model RemoteCourses.Models.Course

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RemoteCourses/Views/Courses/Index.cshtml
@model IEnumerable<RemoteCourses.Models.Course>

@using RemoteCourses.Repositories.EntityFramework;
@{
    ViewBag.Title = "Sekcja kursów";
    Layout = "~/Views/Shared/_Layout.cshtml";


    List<SelectListItem> itemList = new List<SelectListItem>();

    var context = new CourseContext();

    foreach (var course in context.Courses)
    {
        itemList.Add(new SelectListItem() { Text = course.Title, Value = course.Id.ToString() });
    }
}

<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="../img/bg.jpg">
    <div class="container hero-text text-white">
        
        <h2>Moje kursy</h2>

        <table class="table">
            <tr>
                <th>
                    Kategoria
                </th>
                <th>
                    Opis
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.ActionLink("Wybierz", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Wypisz się", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

            <h3>Zapisz się na kurs</h3>

            @using (Html.BeginForm("Index", "Courses", FormMethod.Post))
            {
                <div class="form-actions no-color">
                    <div class="form-inline">
                        @Html.DropDownList("courseId", new SelectList(itemList, "Value", "Text"), "Wybierz Kurs", new { @class = "form-control" })
                        <input type="submit" value="Zapisz" class="btn btn-info" />
                    </div>
                </div>
            }

        </table>
    </div>
</section>
<!-- Hero section end -->