RemoteCourses/Controllers/CoursesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;
using RemoteCourses.Repositories.EntityFramework;
using RemoteCourses.Utils;

namespace RemoteCourses.Controllers
{
    public class CoursesController : Controller
    {
        private CourseContext db = new CourseContext();

        // GET: Courses
        public ActionResult Index(string courseId)
        {
            var name = GetAuthStudent();

            if (courseId != null && courseId != "")
            {
                var id = int.Parse(courseId);
                var course = db.Courses.FirstOrDefault(c => c.Id == id);
                var student = db.Students.FirstOrDefault(s => s.Name == name);

                student.Courses.Add(course);
                db.SaveChanges();
            }

            var courses = db.Courses.Where(c => c.Students.Any(s => s.Name == name)).Include(c => c.Section);

            return View(courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var course = db.Courses.Include(c => c.Section).FirstOrDefault(x => x.Id == id);

            if (course == null)
            {
                return HttpNotFound();
            }

            return View(course);
        }

        //// GET: Courses/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Courses/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Title,Description")] Course course)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Courses.Add(course);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(course);
        //}

        //// GET: Courses/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Course course = db.Courses.Find(id);
        //    if (course == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(course);
        //}

        //// POST: Courses/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Title,Description")] Course course)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(course).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(course);
        //}

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var name = GetAuthStudent();

            var course = db.Courses.FirstOrDefault(c => c.Id == id);
            var student = db.Students.FirstOrDefault(s => s.Name == name);

            student.Courses.Remove(course);
            db.SaveChanges();

            var courses = db.Courses.Where(c => c.Students.Any(s => s.Name == name)).Include(c => c.Section);

            return RedirectToAction("Index");
        }

        //// POST: Courses/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Course course = db.Courses.Find(id);
        //    db.Courses.Remove(course);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        

        // USUNAC DELETE W KURSACH


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string GetAuthStudent()
        {
            var cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            var studnet = AccountUtils.AuthenticatedUser(cookie);

            return studnet != null ? studnet.Name : null;
        }
    }
}

RemoteCourses/Controllers/ResultsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;
using RemoteCourses.Models;
using RemoteCourses.Repositories.EntityFramework;
using RemoteCourses.Utils;

namespace RemoteCourses.Controllers
{
    public class ResultsController : Controller
    {
        private CourseContext db = new CourseContext();

        // GET: Results
        public ActionResult Index()
        {
            var student = GetAuthStudent();

            var results = db.Results.Where(c => c.Student.Name == student).Include(r => r.Student);

            //var results = db.Results.Include(r => r.Student);
            return View(results.ToList());
        }

        // GET: Results/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // GET: Results/Create
        public ActionResult Create()
        {
            ViewBag.Student_Id = new SelectList(db.Students, "Id", "Name");
            return View();
        }

        // POST: Results/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Score,TotalQuestions,DateTaken,Student_Id")] Result result)
        {
            if (ModelState.IsValid)
            {
                db.Results.Add(result);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Student_Id = new SelectList(db.Students, "Id", "Name", result.Student_Id);
            return View(result);
        }

        // GET: Results/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            ViewBag.Student_Id = new SelectList(db.Students, "Id", "Name", result.Student_Id);
            return View(result);
        }

        // POST: Results/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Score,TotalQuestions,DateTaken,Student_Id")] Result result)
        {
            if (ModelState.IsValid)
            {
                db.Entry(result).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Student_Id = new SelectList(db.Students, "Id", "Name", result.Student_Id);
            return View(result);
        }

        // GET: Results/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // POST: Results/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Result result = db.Results.Find(id);
            db.Results.Remove(result);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string GetAuthStudent()
        {
            var cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            var student = AccountUtils.AuthenticatedUser(cookie);

            return student != null ? student.Name : null;
        }
    }
}

RemoteCourses/Controllers/StudentsController.cs
using System.Web.Mvc;
using System.Web.Security;
using RemoteCourses.Models;
using RemoteCourses.Repositories.EntityFramework;
using RemoteCourses.Utils;

namespace RemoteCourses.Controllers
{
    public class StudentsController : Controller
    {
        private CourseContext db = new CourseContext();

        public StudentsController()
        {

        }

        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            var newUser = new Student();

            return View(newUser);
        }

        [HttpPost]
        public ActionResult Login(Student user)
        {
            AccountUtils.UserAuthentication(db, user);

            return View();
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Register()
        {
            var newUser = new Student();

            return View(newUser);
        }

        [HttpPost]
        public ActionResult Register(Student user)
        {
            if (AccountUtils.isUserRegistered(db, user))
            {
                TempData["Message"] = "Nazwa użytkownika lub email są już wykorzystywane przez innego uzytkownika.";
                return View();
            }
            else
            {
                db.Students.Add(new Student
                {
                    Name = user.Name,
                    Email = user.Email,
                    Password = user.Password
                });

                db.SaveChanges();

                if (AccountUtils.UserAuthentication(db, user))
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["Message"] = "Nieporawne dane logowania.";
                    return View();
                }
            }
        }

        public ActionResult UserAuth()
        {
            var cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            
            Student user = AccountUtils.AuthenticatedUser(cookie);
            
            return PartialView(user);
        }
    }
}

RemoteCourses/Views/Shared/UserAuth.cshtml
@model RemoteCourses.Models.Student


@if (Model != null)
{
    using (Html.BeginForm("LogOut", "Students", FormMethod.Post, new { id = "logoutForm", @class = "my-2 my-lg-0" }))
    {
        @Html.AntiForgeryToken()
        <li>@Html.ActionLink("Moje kursy", "Index", "Courses")</li>
        <li>@Html.ActionLink("Moje wyniki", "Index", "Results")</li>
        <form class="my-2 my-lg-0">
            <ul class="mr-auto navbar-right">
                <li class="nav-item">
                    <a class="site-btn header-btn">@Model.Name</a>
                </li>
                <li class="nav-item">
                    <a class="site-btn header-btn" href="@Url.Action("LogOut", "Students")">Wyloguj</a>
                </li>
            </ul>
        </form>
    }
}
else
{
    <form class="my-2 my-lg-0">
        <ul class="mr-auto navbar-right">
            <li class="nav-item">
                <a class="site-btn header-btn" href="@Url.Action("Register", "Students")">Zarejestruj</a>
            </li>
            <li class="nav-item">
                <a class="site-btn header-btn" href="@Url.Action("Login", "Students")">Zaloguj</a>
            </li>
        </ul>
    </form>
}

RemoteCourses/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Kursy Online</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="shortcut icon" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/owl.carousel.css" />
    <link rel="stylesheet" href="~/css/style.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="site-logo">
                        <img src="~/img/logo.png" alt="">
                    </div>
                    <div class="nav-switch">
                        <i class="fa fa-bars"></i>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9">
                    <nav class="main-menu">
                        <ul>
                            <li>@Html.ActionLink("Strona domowa", "Index", "Home")</li>
                            <li>@{Html.RenderAction("UserAuth", "Students");}</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header section end -->
    
    @RenderBody()

    <!-- footer section -->
    <footer class="footer-section spad pb-0">
        <div class="footer-top">
            <div class="footer-warp">
                <div class="row">
                    <div class="widget-item">
                        <h4>Kontakt</h4>
                        <ul class="contact-list">
                            <li>Politechnika Koszalińska</li>
                            <li>wojtyniak.damian@gmail.com</li>
                            <p>&copy; @DateTime.Now.Year - Kursy Online</p>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer section end -->
    <!--====== Javascripts & Jquery ======-->
    <script src="~/js/jquery-3.2.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/mixitup.min.js"></script>
    <script src="~/js/circle-progress.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>